name: Build Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "personalfinancechecking/**"   # chỉ trigger khi backend thay đổi

  pull_request:
    branches: [ "main" ]
    paths:
      - "personalfinancechecking/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: personalfinancechecking   # <-- QUAN TRỌNG

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build backend with Maven
        run: mvn -B clean package -DskipTests
        
      - name: Build Docker Image
        run: docker build -t finance/api-repo:latest .
